# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

###### TWIG EXTENSIONS #####

    app.twig.twig_asset_version_extension:
        class: AppBundle\Twig\AssetVersionExtension
        arguments: ["%kernel.root_dir%"]
        tags:
            - { name: twig.extension }

